import "./readme.css";

function ReadmeApp({ appId }) {
  return (
    <div className="readme px-4 py-3 flex flex-col gap-[0.75rem]">
      <div className="intro flex flex-col gap-[0.5em] py-4">
        <h1 className="text-3xl mb-4">🪟 Windows Web</h1>
        <p className="">
          Welcome to <span className="font-semibold">Windows Web</span>, a fully
          web-based recreation of the Windows desktop experience built from
          scratch using modern web technologies.
        </p>
        <p className="highlight-text mt-2">
          This project is a personal showcase of design, interactivity, and
          frontend system architecture skills, inspired by the aesthetics and
          behavior of Windows 10/11.
        </p>
        <p className="highlight-text mt-2">
          This Readme app's data is generated by ChatGPT
        </p>
      </div>

      <hr />

      <div className="dev-info flex flex-col gap-4 py-4">
        <h2 className="text-xl">👨‍💻 Developer Info</h2>

        <p className="">
          Made with effort, caffeine, and curiosity by Aanshik Sharma
        </p>

        <ul className="flex flex-col gap-1.5 text-sm">
          <li>📍 JSS Academy of Technical Education, Noida</li>
          <li>
            📧 EMail -{" "}
            <a target="blank" href="mailto:aanshik16@gmail.com">
              aanshik16@gmail.com
            </a>
          </li>
          <li>
            🌐 Portfolio -{" "}
            <a target="_blank" href="/">
              aanshik.dev
            </a>
          </li>
          <li>
            🐙 GitHub -{" "}
            <a target="_blank" href="https://github.com/aanshiksharma">
              github.com/aanshiksharma
            </a>
          </li>
        </ul>
      </div>

      <hr />

      <div className="tech-stack flex flex-col gap-4 py-4">
        <h2 className="text-xl">🧰 Tech Stack</h2>

        <ul className="flex flex-col gap-1.5 text-sm">
          <li>
            <span className="font-semibold">React + Vite</span> - App structure
            and rendering
          </li>
          <li>
            <span className="font-semibold">TailwindCSS</span> - Rapid,
            responsive styling
          </li>
          <li>
            <span className="font-semibold">Custom CSS</span> - For component
            precision and polish
          </li>
          <li>
            <span className="font-semibold">LocalStorage & JSON</span> - For
            dummy backend simulation
          </li>
          <li>
            <span className="font-semibold">Icons</span> - Bootstrap Icons,
            Material Icons
          </li>
          <li>
            <span className="font-semibold">Animations</span> - Subtle effects
            to mimic native behavior
          </li>
        </ul>
      </div>

      <hr />

      <div className="feats flex flex-col gap-4 py-4">
        <h2 className="text-xl">🧪 Features</h2>

        <ul className="flex flex-col gap-1.5 text-sm">
          <li>🔒 Login system with authentication simulation</li>
          <li>🪟 Draggable, resizable app windows (just like native OS)</li>
          <li>🧱 Start Menu with pinned apps and search</li>
          <li>⚙️ Settings app with customization options</li>
          <li>
            🗃️ Pre-installed apps (like Calculator, README viewer, Terminal)
          </li>
          <li>🧠 JSON-based dynamic app management (add/remove apps)</li>
          <li>🌗 Dark/light mode transitions (Phase 2)</li>
          <li>
            🐚 Easter eggs in Terminal - try typing `credits` or `whoami`!
          </li>
        </ul>
      </div>

      <hr />

      <div className="license flex flex-col gap-4 py-4">
        <h2 className="text-xl">📜 License & Usage</h2>

        <div className="flex flex-col gap-2">
          <p>
            This project is open for learning, feedback, and inspiration. You
            are free to fork and explore, but please include attribution if
            reused in public or commercial projects.
          </p>

          <p className="highlight-text">
            ⚠️ "All logos and names resembling Microsoft products are for
            educational / demo purposes only."
          </p>
        </div>
      </div>

      <hr />

      <div className="credits flex flex-col gap-4 py-4">
        <h2 className="text-xl">🏆 Credits</h2>

        <ul className="flex flex-col gap-1.5 text-sm">
          <li>Windows UX inspiration - Microsoft</li>
          <li>
            Icons - <a href="icons.getbootstrap.com">Bootstrap Icons</a>
          </li>
          <li>
            Font - <a href="/">[Link Here]</a>
          </li>

          <li>Browser environment - All hail the DOM gods 🙌</li>
        </ul>
      </div>

      <hr />

      <div className="final-note flex flex-col gap-4 py-4">
        <h2 className="text-xl">📌 Final Note</h2>

        <p>
          This OS may not *boot* your real computer, but it boots up the best in
          me.
        </p>
        <p className="highlight-text">
          Explore it. Break it. Reboot it. And if you love it, star the repo or
          drop a message 😄
        </p>
      </div>
    </div>
  );
}

export default ReadmeApp;
